debug: true
server:
  port: 9080

spring:
  application:
    name: course-service
#  datasource:
#     url: jdbc:mysql://course-db:3307/course_data?useSSL=false&createDatabaseIfNotExist=true
#     username: sa
#     password: yourPassword
#     testWhileIdle: true
#     validationQuery: SELECT 1
#     driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#     show-sql: true
#     properties:
#        hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#     hibernate:
#        ddl-auto: update
#        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

    
data-auth:
   client-name: ${KEYCLOAK_CLIENT_ID}
#---------------------------------------------------
#Deployment on in kubernetes      
#---------------------------------------------------
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
       defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

      
#---------------------------------------------------
#Deployment on localhost      
#---------------------------------------------------
#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#       defaultZone: ${DISCOVERY}
       

