apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: fabianhalbig/gateway:gcp
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_SERVICE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: keycloak_service_address
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: keycloak_realm
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: keycloak_client_id
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: keycloak_client_secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: gateway
