apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: keycloak-db
          image: postgres:10
          resources:
            limits:
              cpu: "1"
              memory: "4Gi"
            requests:
              cpu: "1"
              memory: "4Gi"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: keycloakUser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: keycloak-pv
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
spec:
  ports:
    - port: 5432
  selector:
    app: keycloak-db
  clusterIP: None
