apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: fabianhalbig/user-service:gcp
          imagePullPolicy: Always
          ports:
            - containerPort: 9070
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://status-db:5432/status
            - name: SPRING_DATASOURCE_USERNAME
              value: statusUser
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_DATABASE-PLATFORM
              value: org.hibernate.dialect.PostgreSQLDialect
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - targetPort: 9070
      port: 80
  selector:
    app: user-service
