server:
  port: 8761

#---------------------------------------------------
#Deployment on docker
#---------------------------------------------------
#eureka:
#  instance:
#    hostname: discovery
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://discovery:${server.port}/eureka/
#---------------------------------------------------
#Deployment on localhost
#---------------------------------------------------
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#       defaultZone: http://localhost:8761/eureka/

eureka:
  instance:
    hostname: "${HOSTNAME}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
